# Generated by Django 3.2.7 on 2021-09-30 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=25)),
                ('birthdate', models.DateField()),
                ('mobile_number', models.DateField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('dvd_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=25)),
                ('release_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='midterm.customer')),
                ('dvd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='midterm.dvd')),
            ],
        ),
    ]
