# Generated by Django 3.2.7 on 2021-09-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midterm', '0002_auto_20210930_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
