# Generated by Django 3.2.7 on 2021-09-30 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('midterm', '0004_rename_car_id_customer_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
