# Generated by Django 3.2.7 on 2021-09-30 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('midterm', '0006_auto_20210930_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='midterm.customer'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='dvd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='midterm.dvd'),
        ),
    ]
